// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('TodoApp').controller('TodoController', function($scope) {
    var guid, removeById, s4;
    s4 = function() {
      return Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
    };
    guid = function() {
      return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4();
    };
    removeById = function(search_term, array) {
      var index;
      index = array.map(function(e) {
        return e.id;
      }).indexOf(search_term);
      if (index !== -1) {
        return array.splice(index, 1);
      }
    };
    $scope.newTodo = "Learn Angular";
    $scope.todos = [
      {
        description: "read angular ebook",
        id: guid()
      }, {
        description: "add e2e tests",
        id: guid()
      }
    ];
    $scope.add = function() {
      $scope.todos.push({
        description: $scope.newTodo,
        id: guid()
      });
      return $scope.newTodo = '';
    };
    return $scope.remove = function(id) {
      return removeById(id, $scope.todos);
    };
  });

}).call(this);
